//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Create a Detailed Budget..
        /// </summary>
        public static string Tip1 {
            get {
                return ResourceManager.GetString("Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Set Realistic Goals..
        /// </summary>
        public static string Tip2 {
            get {
                return ResourceManager.GetString("Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Track Daily Expenses..
        /// </summary>
        public static string Tip3 {
            get {
                return ResourceManager.GetString("Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Check statistic of your transactions..
        /// </summary>
        public static string Tip4 {
            get {
                return ResourceManager.GetString("Tip4", resourceCulture);
            }
        }
        public static string Link1
        {
            get
            {
                return ResourceManager.GetString("Link1", resourceCulture);
            }
        }
        public static string Link2
        {
            get
            {
                return ResourceManager.GetString("Link2", resourceCulture);
            }
        }
        public static string Link3
        {
            get
            {
                return ResourceManager.GetString("Link3", resourceCulture);
            }
        }
        public static string TipsTricks
        {
            get
            {
                return ResourceManager.GetString("TipsTricks", resourceCulture);
            }
        }
        public static string Btn_back
        {
            get
            {
                return ResourceManager.GetString("Btn_back", resourceCulture);
            }
        }
        public static string CategoryLabel
        {
            get
            {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        public static string ExpenseLabel
        {
            get
            {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture);
            }
        }
        public static string TransactionNameLabel
        {
            get
            {
                return ResourceManager.GetString("TransactionNameLabel", resourceCulture);
            }
        }
        public static string CostLabel
        {
            get
            {
                return ResourceManager.GetString("CostLabel", resourceCulture);
            }
        }
        public static string Btn_save
        {
            get
            {
                return ResourceManager.GetString("Btn_save", resourceCulture);
            }
        }
        public static string StartDateLabel
        {
            get
            {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        public static string EndDataLabel
        {
            get
            {
                return ResourceManager.GetString("EndDataLabel", resourceCulture);
            }
        }
        public static string SelectPeriodLabel
        {
            get
            {
                return ResourceManager.GetString("SelectPeriodLabel", resourceCulture);
            }
        }
        public static string SelectCategoryLabel
        {
            get
            {
                return ResourceManager.GetString("SelectCategoryLabel", resourceCulture);
            }
        }
        public static string SelectTypeDataLabel
        {
            get
            {
                return ResourceManager.GetString("SelectTypeDataLabel", resourceCulture);
            }
        }
        public static string Btn_export
        {
            get
            {
                return ResourceManager.GetString("Btn_export", resourceCulture);
            }
        }
        public static string LanguageLabel
        {
            get
            {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        public static string ChooseThemeLabel
        {
            get
            {
                return ResourceManager.GetString("ChooseThemeLabel", resourceCulture);
            }
        }
        public static string CurencyLabel
        {
            get
            {
                return ResourceManager.GetString("CurencyLabel", resourceCulture);
            }
        }
        public static string SettingsLabel
        {
            get
            {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
    }
}
